/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author JULIAN C
 * Fechas: https://www.delftstack.com/es/howto/java/how-to-get-the-current-date-time-in-java/
 * ctrl + shift + i : shorcut para importar
 */
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class RegistrarView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVenta
     */
    public RegistrarView() {
        initComponents();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yy/MM/dd HH:mm:ss");
        textFechaHora.setText(dtf.format(LocalDateTime.now()));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroDatos = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelContenido = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        textFechaHora = new javax.swing.JTextField();
        CbxUsuario = new javax.swing.JComboBox<>();
        CbxContenido = new javax.swing.JComboBox<>();
        botonEliminar = new javax.swing.JButton();
        labelIdUsuario = new javax.swing.JLabel();
        textIdBiblioteca = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        labelControlDeCambio = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistroDatos.setBackground(new java.awt.Color(153, 153, 153));
        panelRegistroDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de datos"));
        panelRegistroDatos.setToolTipText("");
        panelRegistroDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsuario.setText("Usuario:");
        panelRegistroDatos.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        labelContenido.setText("Contenido:");
        panelRegistroDatos.add(labelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, -1));

        labelFecha.setText("Fecha:");
        panelRegistroDatos.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        botonAgregar.setText("Agregar");
        panelRegistroDatos.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 95, -1));

        textFechaHora.setEditable(false);
        textFechaHora.setBorder(null);
        panelRegistroDatos.add(textFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 110, -1));

        CbxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        panelRegistroDatos.add(CbxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, -1));

        CbxContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        panelRegistroDatos.add(CbxContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 130, -1));

        botonEliminar.setText("Eliminar");
        panelRegistroDatos.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 95, -1));

        labelIdUsuario.setText("Id Registro: ");
        panelRegistroDatos.add(labelIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        panelRegistroDatos.add(textIdBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, -1));

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        panelRegistroDatos.add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 95, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/teRetoAProgramarlo.png"))); // NOI18N
        panelRegistroDatos.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 56));

        labelControlDeCambio.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelControlDeCambio.setText("Control de cambios");
        panelRegistroDatos.add(labelControlDeCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        getContentPane().add(panelRegistroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 280));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/fondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxContenido;
    private javax.swing.JComboBox<String> CbxUsuario;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel labelContenido;
    private javax.swing.JLabel labelControlDeCambio;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelIdUsuario;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelRegistroDatos;
    private javax.swing.JTextField textFechaHora;
    private javax.swing.JTextField textIdBiblioteca;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbxContenido() {
        return CbxContenido;
    }

    public void setCbxContenido(JComboBox<String> CbxContenido) {
        this.CbxContenido = CbxContenido;
    }

    public JComboBox<String> getCbxUsuario() {
        return CbxUsuario;
    }

    public void setCbxUsuario(JComboBox<String> CbxUsuario) {
        this.CbxUsuario = CbxUsuario;
    }

    public JButton getBotonAgregar() {
        return botonAgregar;
    }

    public void setBotonAgregar(JButton botonAgregar) {
        this.botonAgregar = botonAgregar;
    }

    public JButton getBotonActualizar() {
        return botonActualizar;
    }

    public void setBotonActualizar(JButton botonActualizar) {
        this.botonActualizar = botonActualizar;
    }

    public JButton getBotonEliminar() {
        return botonEliminar;
    }

    public void setBotonEliminar(JButton botonEliminar) {
        this.botonEliminar = botonEliminar;
    }

    public JTextField getTextFechaHora() {
        return textFechaHora;
    }

    public void setTextFechaHora(JTextField textFechaHora) {
        this.textFechaHora = textFechaHora;
    }

    public JTextField getTextIdBiblioteca() {
        return textIdBiblioteca;
    }

    public void setTextIdBiblioteca(JTextField textIdBiblioteca) {
        this.textIdBiblioteca = textIdBiblioteca;
    }

    public JLabel getLabelIdUsuario() {
        return labelIdUsuario;
    }

//    public void setLabelIdUsuario(JLabel labelIdUsuario) {
//        this.labelIdUsuario = labelIdUsuario;
//    }
}
