/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author JULIAN C
 */
public class VistaRegistrosView extends javax.swing.JFrame {

    /**
     * Creates new form ClienteVista
     */
    public VistaRegistrosView() {
        initComponents();
        this.getIconImage();        
    }

    @Override
    public final Image getIconImage() {
        Image iconoApp = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("utils/imgs/icono.jpg"));
        return iconoApp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_datos = new javax.swing.JPanel();
        labelBusqUsuario = new javax.swing.JLabel();
        botonVerRegistros = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        tituloP1 = new javax.swing.JLabel();
        botonAgregarRegistro = new javax.swing.JButton();
        labelBusqTitulo = new javax.swing.JLabel();
        CbxContenido = new javax.swing.JComboBox<>();
        CbxFecha = new javax.swing.JComboBox<>();
        CbxUsuario = new javax.swing.JComboBox<>();
        labelBusqFeha = new javax.swing.JLabel();
        botonModificarRegistro = new javax.swing.JButton();
        jPanel_Detalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista de Cliente");
        setPreferredSize(new java.awt.Dimension(800, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_datos.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel_datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBusqUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelBusqUsuario.setText("Usuario:");
        jPanel_datos.add(labelBusqUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        botonVerRegistros.setText("Ver Registros");
        botonVerRegistros.setFocusPainted(false);
        jPanel_datos.add(botonVerRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 40));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/teRetoAProgramarlo.png"))); // NOI18N
        jPanel_datos.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 280, 80));

        tituloP1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        tituloP1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tituloP1.setText("Sistema de control de registros de Bibliotecas");
        jPanel_datos.add(tituloP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 400, 50));

        botonAgregarRegistro.setText("Agregar Registro");
        botonAgregarRegistro.setFocusPainted(false);
        jPanel_datos.add(botonAgregarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 30));

        labelBusqTitulo.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelBusqTitulo.setText("Contenido:");
        jPanel_datos.add(labelBusqTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 20));

        CbxContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        jPanel_datos.add(CbxContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 130, -1));

        CbxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        jPanel_datos.add(CbxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, -1));

        CbxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        jPanel_datos.add(CbxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 130, -1));

        labelBusqFeha.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        labelBusqFeha.setText("Fecha:");
        jPanel_datos.add(labelBusqFeha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 20));

        botonModificarRegistro.setText("Modificar Registro");
        botonModificarRegistro.setFocusPainted(false);
        jPanel_datos.add(botonModificarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        getContentPane().add(jPanel_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 160));

        jPanel_Detalle.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_Detalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tablaDetalle.setAutoCreateRowSorter(true);
        tablaDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Registro", "Fecha", "Usuario", "Nombre", "ID Contenido", "Contenido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDetalle);

        javax.swing.GroupLayout jPanel_DetalleLayout = new javax.swing.GroupLayout(jPanel_Detalle);
        jPanel_Detalle.setLayout(jPanel_DetalleLayout);
        jPanel_DetalleLayout.setHorizontalGroup(
            jPanel_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetalleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_DetalleLayout.setVerticalGroup(
            jPanel_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetalleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 770, 220));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/fondo.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxContenido;
    private javax.swing.JComboBox<String> CbxFecha;
    private javax.swing.JComboBox<String> CbxUsuario;
    private javax.swing.JButton botonAgregarRegistro;
    private javax.swing.JButton botonModificarRegistro;
    private javax.swing.JButton botonVerRegistros;
    private javax.swing.JPanel jPanel_Detalle;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBusqFeha;
    private javax.swing.JLabel labelBusqTitulo;
    private javax.swing.JLabel labelBusqUsuario;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JLabel tituloP1;
    // End of variables declaration//GEN-END:variables

    
    public JComboBox<String> getCbxContenido() {
        return CbxContenido;
    }

    public void setCbxContenido(JComboBox<String> CbxContenido) {
        this.CbxContenido = CbxContenido;
    }

    public JComboBox<String> getCbxFecha() {
        return CbxFecha;
    }

    public void setCbxFecha(JComboBox<String> CbxFecha) {
        this.CbxFecha = CbxFecha;
    }

    public JComboBox<String> getCbxUsuario() {
        return CbxUsuario;
    }

    public void setCbxUsuario(JComboBox<String> CbxUsuario) {
        this.CbxUsuario = CbxUsuario;
    }

    public JTable getTablaDetalle() {
        return tablaDetalle;
    }

    public void setTablaDetalle(JTable tablaDetalle) {
        this.tablaDetalle = tablaDetalle;
    }

    public JButton getBotonAgregarRegistro() {
        return botonAgregarRegistro;
    }
    
    public JButton getBotonModificarRegistro() {
        return botonModificarRegistro;
    }

    public JButton getBotonVerRegistros() {
        return botonVerRegistros;
    }
}
