# Generated by Django 3.2.8 on 2021-10-31 23:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='nombre')),
                ('documento', models.FloatField(unique=True, verbose_name='documento')),
            ],
        ),
        migrations.CreateModel(
            name='Miscelanea',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_misc', models.CharField(max_length=45, verbose_name='nombre_miscelanea')),
                ('direccion_misc', models.CharField(max_length=150, unique=True, verbose_name='direccion_miscelanea')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=45, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=200, verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cliente', to='g6App.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo_barras', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha_vencimiento')),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='fecha_ingreso')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio_compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio_venta')),
                ('id_miscelanea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscelanea', to='g6App.miscelanea')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_producto', to='g6App.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_venta', models.FloatField(default=0, verbose_name='precio')),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_inventario', to='g6App.inventario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_venta', to='g6App.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='username')),
                ('nombre', models.CharField(max_length=45, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='cedula')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='dateTime')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('miscelanea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_trabajo', to='g6App.miscelanea')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
